changes taken from branch 'continuous_database_backup'
fairagro/basic_infrastructure pull request #94
Opened 2024-12-23 14:57 UTC by Zalfsten

some improvements from branch 'continuous_database_backup' without taken the actual backup-related changes

2025-01-08 12:21 UTC, darnold-zalf commented on .devcontainer/devcontainer.json
Note: going back 1 minor revision point

2025-01-08 12:22 UTC, darnold-zalf commented on .gitignore
VScode bug maybe - no differences here ..

2025-01-08 12:23 UTC, darnold-zalf commented on README.md
Pls doublecheck the changes here

2025-01-08 12:28 UTC, darnold-zalf commented on environments/fizz/values/fairagro-applications.yaml
This should be HEAD not the <branch name>

2025-01-08 12:31 UTC, darnold-zalf commented on environments/fizz/values/zalf-nextcloud.yaml
This sets a flag for various charts to enable backups

2025-01-08 12:39 UTC, darnold-zalf requested changes
Please doublecheck this, noting my comments where applicable.

2025-01-08 13:02 UTC, Zalfsten commented on .devcontainer/devcontainer.json
fixed

2025-01-08 13:02 UTC, Zalfsten commented on .gitignore
nothing to do

2025-01-08 13:03 UTC, Zalfsten commented on README.md
This is intend. The README from main is outdated

2025-01-13 08:26 UTC, darnold-zalf approved these changes
Noted comments from Carsten and approve this MR.

2025-01-13 08:53 UTC, merged